import Head from 'next/head'
import CoinList from '../components/CoinList.js'
import Layout from '../components/Layout.js'
import SearchBar from '../components/SearchBar.js/index.js'
import { useState } from 'react'




export default function Home({filteredCoins}) {
  const [search, setSearch] = useState('');

  const allCoins = filteredCoins.filter(coin =>
    coin.name.toLowerCase().includes(search.toLowerCase())
  );

  const handleChange = e => {
    e.preventDefault();

    setSearch(e.target.value.toLowerCase());
  };
  return (
    <Layout >
      <Head>
        <title>Crypto tracker </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<SearchBar type = "text" placeholder = "search" onChange = {handleChange}></SearchBar>
    <CoinList filteredCoins = {allCoins}></CoinList>
    </Layout>
  )
}
 
export const getServerSideProps = async () => {
  const res = await fetch(' https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false')
 const filteredCoins = await res.json() 


 return {
props : {
  filteredCoins

}
 }
}